First, we import packages.

In [21]:
import pandas as pd
from pathlib import Path
pd.set_option('future.no_silent_downcasting', True)

Then, we provide the data from .csv to pandas dataframes (remember to first download the files into data/raw folder and unzip it there).

In [22]:
PROJECT_ROOT = Path.cwd()
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"

In [23]:
df_train = pd.read_csv(RAW_DATA_DIR / "train.csv")
df_test = pd.read_csv(RAW_DATA_DIR / "test.csv")
df_train

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [24]:
df_test

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [25]:
df_train.columns.values

array(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination',
       'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa',
       'VRDeck', 'Name', 'Transported'], dtype=object)

Let's find out what values does each column contain.

In [26]:
for column in df_train.columns.values:
    print(f"Unique values in column {column} are: {df_train[column].unique()}")

Unique values in column PassengerId are: ['0001_01' '0002_01' '0003_01' ... '9279_01' '9280_01' '9280_02']
Unique values in column HomePlanet are: ['Europa' 'Earth' 'Mars' nan]
Unique values in column CryoSleep are: [False True nan]
Unique values in column Cabin are: ['B/0/P' 'F/0/S' 'A/0/S' ... 'G/1499/S' 'G/1500/S' 'E/608/S']
Unique values in column Destination are: ['TRAPPIST-1e' 'PSO J318.5-22' '55 Cancri e' nan]
Unique values in column Age are: [39. 24. 58. 33. 16. 44. 26. 28. 35. 14. 34. 45. 32. 48. 31. 27.  0.  1.
 49. 29. 10.  7. 21. 62. 15. 43. 47.  2. 20. 23. 30. 17. 55.  4. 19. 56.
 nan 25. 38. 36. 22. 18. 42. 37. 13.  8. 40.  3. 54.  9.  6. 64. 67. 61.
 50. 41. 57. 11. 52. 51. 46. 60. 63. 59.  5. 79. 68. 74. 12. 53. 65. 71.
 75. 70. 76. 78. 73. 66. 69. 72. 77.]
Unique values in column VIP are: [False True nan]
Unique values in column RoomService are: [   0.  109.   43. ... 1569. 8586.  745.]
Unique values in column FoodCourt are: [   0.    9. 3576. ... 3208. 6819. 4688.]
Unique values in column ShoppingMall are: [   0.   25.  371. ... 1085.  510. 1872.]
Unique values in column Spa are: [   0.  549. 6715. ... 2868. 1107. 1643.]
Unique values in column VRDeck are: [   0.   44.   49. ... 1164.  971. 3235.]
Unique values in column Name are: ['Maham Ofracculy' 'Juanna Vines' 'Altark Susent' ... 'Fayey Connon'
 'Celeon Hontichre' 'Propsh Hontichre']
Unique values in column Transported are: [False  True]

First, we want to take the number of people in each group ID

In [27]:
for df in [df_train, df_test]:
    df['NumberGroup'] = df['PassengerId'].str.split('_').str[1]
    df['NumberGroup'] = df['NumberGroup'].astype(int)

In [28]:
df_train

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,NumberGroup
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,1
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,1
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False,1
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,2
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False,1
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False,1
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True,1
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False,1
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True,2

Now we want to fill missing values and perform one-hot-encoding on column HomePlanet.

In [29]:
missingHP='MissingHP'

def encode_homeplanet(df):
    df = df.copy()
    df['HomePlanet'] = df['HomePlanet'].fillna(missingHP)
    one_hot = pd.get_dummies(df['HomePlanet'], prefix='HomePlanet')
    df = df.drop('HomePlanet', axis=1).join(one_hot)
    return df

df_train = encode_homeplanet(df_train)
df_test  = encode_homeplanet(df_test)

In [30]:
df_train

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,NumberGroup,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,HomePlanet_MissingHP
0,0001_01,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,1,False,True,False,False
1,0002_01,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,1,True,False,False,False
2,0003_01,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False,1,False,True,False,False
3,0003_02,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,2,False,True,False,False
4,0004_01,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,1,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False,1,False,True,False,False
8689,9278_01,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False,1,True,False,False,False
8690,9279_01,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True,1,True,False,False,False
8691,9280_01,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False,1,False,True,False,False
8692,9280_02,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True,2,False,True,False,False

We want to handle missing values in CryoSleep column. There are not many of them, so we fill with the most used boolean value.

In [31]:
most_common_cryosleep = df_train['CryoSleep'].mode()[0]

for df in [df_train, df_test]:
    df['CryoSleep'] = df['CryoSleep'].fillna(most_common_cryosleep)

In [32]:
df_train

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,NumberGroup,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,HomePlanet_MissingHP
0,0001_01,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,1,False,True,False,False
1,0002_01,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,1,True,False,False,False
2,0003_01,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False,1,False,True,False,False
3,0003_02,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,2,False,True,False,False
4,0004_01,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,1,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False,1,False,True,False,False
8689,9278_01,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False,1,True,False,False,False
8690,9279_01,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True,1,True,False,False,False
8691,9280_01,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False,1,False,True,False,False
8692,9280_02,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True,2,False,True,False,False

Now we want to transform the Cabin column into three different columns.

In [33]:
def encode_cabin(df):
    df = df.copy()
    df['CabinDeck'] = df['Cabin'].str.split('/').str[0]
    df['CabinNum'] = df['Cabin'].str.split('/').str[1]
    df['CabinSide'] = df['Cabin'].str.split('/').str[2]
    return df

df_train = encode_cabin(df_train)
df_test = encode_cabin(df_test)

In [34]:
df_train

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,...,Name,Transported,NumberGroup,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,HomePlanet_MissingHP,CabinDeck,CabinNum,CabinSide
0,0001_01,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,...,Maham Ofracculy,False,1,False,True,False,False,B,0,P
1,0002_01,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,...,Juanna Vines,True,1,True,False,False,False,F,0,S
2,0003_01,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,...,Altark Susent,False,1,False,True,False,False,A,0,S
3,0003_02,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,...,Solam Susent,False,2,False,True,False,False,A,0,S
4,0004_01,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,...,Willy Santantines,True,1,True,False,False,False,F,1,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,...,Gravior Noxnuther,False,1,False,True,False,False,A,98,P
8689,9278_01,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,...,Kurta Mondalley,False,1,True,False,False,False,G,1499,S
8690,9279_01,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,...,Fayey Connon,True,1,True,False,False,False,G,1500,S
8691,9280_01,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,...,Celeon Hontichre,False,1,False,True,False,False,E,608,S
8692,9280_02,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,...,Propsh Hontichre,True,2,False,True,False,False,E,608,S

In [35]:
most_common_cabindeck = df_train['CabinDeck'].mode()[0]
most_common_cabinnum = df_train['CabinNum'].mode()[0]
most_common_cabinside = df_train['CabinSide'].mode()[0]

def one_hot_cabin(df):

    df['CabinDeck'] = df['CabinDeck'].fillna(most_common_cabindeck)
    df['CabinNum'] = df['CabinNum'].fillna(most_common_cabinnum).astype(int)
    df['CabinSide'] = df['CabinSide'].fillna(most_common_cabinside)

    one_hot1 = pd.get_dummies(df['CabinDeck'], prefix='CabinDeck')
    df = df.drop('CabinDeck', axis=1).join(one_hot1)

    one_hot2 = pd.get_dummies(df['CabinSide'], prefix='CabinSide')
    df = df.drop('CabinSide', axis=1).join(one_hot2)

    df = df.drop('Cabin', axis=1)
    return df

df_train = one_hot_cabin(df_train)
df_test = one_hot_cabin(df_test)

In [36]:
df_train

,PassengerId,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,...,CabinDeck_A,CabinDeck_B,CabinDeck_C,CabinDeck_D,CabinDeck_E,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinSide_P,CabinSide_S
0,0001_01,False,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,...,False,True,False,False,False,False,False,False,True,False
1,0002_01,False,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,...,False,False,False,False,False,True,False,False,False,True
2,0003_01,False,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,...,True,False,False,False,False,False,False,False,False,True
3,0003_02,False,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,...,True,False,False,False,False,False,False,False,False,True
4,0004_01,False,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,False,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,...,True,False,False,False,False,False,False,False,True,False
8689,9278_01,True,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,True,False,False,True
8690,9279_01,False,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,...,False,False,False,False,False,False,True,False,False,True
8691,9280_01,False,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,...,False,False,False,False,True,False,False,False,False,True
8692,9280_02,False,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,...,False,False,False,False,True,False,False,False,False,True

Now we perform one-hot-encoding on Destination.

In [37]:
most_common_destination = df_train['Destination'].mode()[0]

def encode_destination(df):
    df = df.copy()

    df['Destination'] = df['Destination'].fillna(most_common_destination)

    one_hot = pd.get_dummies(df['Destination'], prefix='Destination')
    df = df.drop('Destination', axis=1).join(one_hot)
    return df

df_train = encode_destination(df_train)
df_test  = encode_destination(df_test)

In [38]:
df_train

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,...,CabinDeck_D,CabinDeck_E,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinSide_P,CabinSide_S,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,0001_01,False,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,...,False,False,False,False,False,True,False,False,False,True
1,0002_01,False,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,...,False,False,True,False,False,False,True,False,False,True
2,0003_01,False,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,...,False,False,False,False,False,False,True,False,False,True
3,0003_02,False,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,...,False,False,False,False,False,False,True,False,False,True
4,0004_01,False,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,...,False,False,True,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,False,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,...,False,False,False,False,False,True,False,True,False,False
8689,9278_01,True,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,...,False,False,False,True,False,False,True,False,True,False
8690,9279_01,False,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,...,False,False,False,True,False,False,True,False,False,True
8691,9280_01,False,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,...,False,True,False,False,False,False,True,True,False,False
8692,9280_02,False,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,...,False,True,False,False,False,False,True,False,False,True

Now we will handle with missing values in other columns.

In [39]:
most_common_age = df_train['Age'].mean()
most_common_vip = df_train['VIP'].mode()[0]
most_common_roomservice = df_train['RoomService'].mean()
most_common_foodcourt = df_train['FoodCourt'].mean()
most_common_shoppingmall = df_train['ShoppingMall'].mean()
most_common_spa = df_train['Spa'].mean()
most_common_VRDeck = df_train['VRDeck'].mean()

def missing_rest_values(df):
    df = df.copy()

    df['Age'] = df['Age'].fillna(most_common_age)
    df['VIP'] = df['VIP'].fillna(most_common_vip)
    df['RoomService'] = df['RoomService'].fillna(most_common_roomservice)
    df['FoodCourt'] = df['FoodCourt'].fillna(most_common_foodcourt)
    df['ShoppingMall'] = df['ShoppingMall'].fillna(most_common_spa)
    df['Spa'] = df['Spa'].fillna(most_common_spa)
    df['VRDeck'] = df['VRDeck'].fillna(most_common_VRDeck)

    return df

df_train = missing_rest_values(df_train)
df_test = missing_rest_values(df_test)

In [40]:
df_train

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,...,CabinDeck_D,CabinDeck_E,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinSide_P,CabinSide_S,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,0001_01,False,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,...,False,False,False,False,False,True,False,False,False,True
1,0002_01,False,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,...,False,False,True,False,False,False,True,False,False,True
2,0003_01,False,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,...,False,False,False,False,False,False,True,False,False,True
3,0003_02,False,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,...,False,False,False,False,False,False,True,False,False,True
4,0004_01,False,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,...,False,False,True,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,False,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,...,False,False,False,False,False,True,False,True,False,False
8689,9278_01,True,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,...,False,False,False,True,False,False,True,False,True,False
8690,9279_01,False,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,...,False,False,False,True,False,False,True,False,False,True
8691,9280_01,False,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,...,False,True,False,False,False,False,True,True,False,False
8692,9280_02,False,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,...,False,True,False,False,False,False,True,False,False,True

Now we will handle with Name column - we will count how many names and surnames were encountered. We are careful, bearing in mind we don't want to have data leakage. A new first name / last name in the test data (not encountered in training data) will have its count assigned to 1.

In [41]:
missing_value = 'Missing Missing'

def names_handling(df):
    df = df.copy()
    df['Name'] = df['Name'].fillna(missing_value)
    df[['FirstName', 'LastName']] = df['Name'].str.split(' ', n=1, expand=True)
    return df

df_train = names_handling(df_train)
df_test = names_handling(df_test)

In [42]:
df_train

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,...,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinSide_P,CabinSide_S,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,FirstName,LastName
0,0001_01,False,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,...,False,False,False,True,False,False,False,True,Maham,Ofracculy
1,0002_01,False,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,...,True,False,False,False,True,False,False,True,Juanna,Vines
2,0003_01,False,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,...,False,False,False,False,True,False,False,True,Altark,Susent
3,0003_02,False,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,...,False,False,False,False,True,False,False,True,Solam,Susent
4,0004_01,False,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,...,True,False,False,False,True,False,False,True,Willy,Santantines
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,False,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,...,False,False,False,True,False,True,False,False,Gravior,Noxnuther
8689,9278_01,True,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,...,False,True,False,False,True,False,True,False,Kurta,Mondalley
8690,9279_01,False,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,...,False,True,False,False,True,False,False,True,Fayey,Connon
8691,9280_01,False,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,...,False,False,False,False,True,True,False,False,Celeon,Hontichre
8692,9280_02,False,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,...,False,False,False,False,True,False,False,True,Propsh,Hontichre

In [43]:
first_name_counts = df_train['FirstName'].value_counts()
last_name_counts  = df_train['LastName'].value_counts()

first_name_mean = first_name_counts.drop('Missing', errors='ignore').mean().round()
last_name_mean  = last_name_counts.drop('Missing', errors='ignore').mean().round()

In [44]:
def names_counting(df):
    df = df.copy()

    df['FirstNamesCount'] = df['FirstName'].map(first_name_counts).fillna(1)
    df['LastNamesCount']  = df['LastName'].map(last_name_counts).fillna(1)

    df.loc[df['FirstName'] == 'Missing', 'FirstNamesCount'] = first_name_mean
    df.loc[df['LastName'] == 'Missing', 'LastNamesCount'] = last_name_mean

    df = df.drop(['FirstName', 'LastName', 'Name'], axis=1)
    return df

df_train = names_counting(df_train)
df_test = names_counting(df_test)

In [45]:
df_train

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,...,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinSide_P,CabinSide_S,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,FirstNamesCount,LastNamesCount
0,0001_01,False,39.0,False,0.0,0.0,0.0,0.0,0.0,False,...,False,False,False,True,False,False,False,True,4,1
1,0002_01,False,24.0,False,109.0,9.0,25.0,549.0,44.0,True,...,True,False,False,False,True,False,False,True,6,4
2,0003_01,False,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,...,False,False,False,False,True,False,False,True,1,6
3,0003_02,False,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,...,False,False,False,False,True,False,False,True,3,6
4,0004_01,False,16.0,False,303.0,70.0,151.0,565.0,2.0,True,...,True,False,False,False,True,False,False,True,9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,False,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,...,False,False,False,True,False,True,False,False,2,3
8689,9278_01,True,18.0,False,0.0,0.0,0.0,0.0,0.0,False,...,False,True,False,False,True,False,True,False,4,2
8690,9279_01,False,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,...,False,True,False,False,True,False,False,True,5,6
8691,9280_01,False,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,...,False,False,False,False,True,True,False,False,3,6
8692,9280_02,False,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,...,False,False,False,False,True,False,False,True,3,6

In [46]:
df_test

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,NumberGroup,...,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinSide_P,CabinSide_S,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,FirstNamesCount,LastNamesCount
0,0013_01,True,27.00000,False,0.0,0.0,0.0,0.0,0.0,1,...,False,True,False,False,True,False,False,True,9.0,4.0
1,0018_01,False,19.00000,False,0.0,9.0,0.0,2823.0,0.0,1,...,True,False,False,False,True,False,False,True,6.0,3.0
2,0019_01,True,31.00000,False,0.0,0.0,0.0,0.0,0.0,1,...,False,False,False,False,True,True,False,False,1.0,5.0
3,0021_01,False,38.00000,False,0.0,6652.0,0.0,181.0,585.0,1,...,False,False,False,False,True,False,False,True,3.0,1.0
4,0023_01,False,20.00000,False,10.0,0.0,635.0,0.0,0.0,1,...,True,False,False,False,True,False,False,True,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,True,34.00000,False,0.0,0.0,0.0,0.0,0.0,2,...,False,True,False,False,True,False,False,True,5.0,6.0
4273,9269_01,False,42.00000,False,0.0,847.0,17.0,10.0,144.0,1,...,True,False,False,False,True,False,False,True,1.0,4.0
4274,9271_01,True,28.82793,False,0.0,0.0,0.0,0.0,0.0,1,...,False,False,False,True,False,True,False,False,5.0,1.0
4275,9273_01,False,28.82793,False,0.0,2680.0,0.0,0.0,523.0,1,...,False,False,False,True,False,False,False,True,1.0,2.0
4276,9277_01,True,43.00000,False,0.0,0.0,0.0,0.0,0.0,1,...,False,True,False,False,True,False,True,False,9.0,7.0

In [47]:
target = 'Transported'

X_train = df_train.drop(columns=[target])
y_train = df_train[target]

X_test = df_test.copy()

Final check if everything have right dimensions.

In [48]:
print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')

X_train shape: (8693, 30)
X_test shape: (4277, 30)
y_train shape: (8693,)

In [49]:
RAW_DATA_DIR = PROJECT_ROOT / "data" / "processed"

X_train.to_csv(RAW_DATA_DIR / 'X_train.csv', index=False)
y_train.to_csv(RAW_DATA_DIR / 'y_train.csv', index=False)
X_test.to_csv(RAW_DATA_DIR / 'X_test.csv', index=False)